### ISSUE TITLE
Custom dimensions & metrics

### ISSUE THREAD

**Issue by Okyne** [angulartics/angulartics-google-tag-manager#15]
Hi,

I'm currently using this good plugin. So thank you guys. 
But I'm facing a problem when adding custom variables to my google analytics.

Is there somebody who works actually on a method to add custom variables ?  If not, I could work on it and propose a PR.

Let me know. Bye

**Comment by DanWilkerson** [comment]
We support Custom Dimensions and Metrics - set them as dimensionX or metricX on your properties object.

We don't currently support Custom Variables, and have no plans to do so at the moment - Custom Variables are a deprecated feature from Classic Analytics.

**Comment by Okyne** [comment]
Thank you for your quick answer Dan.
I'm gonna upgrade my Analytics to the Universal version.
