### ISSUE TITLE
Configurable GTM-XXX code

### ISSUE THREAD

**Issue by lerio** [angulartics/angulartics-google-tag-manager#17]
Hi,

would it be possible to add the GTM-XXX code dynamically? I'd like to set different GTM IDs depending on the working environment, so that I can test stuff without polluting the production one. So far I tried few solutions, using the `$scope` variable or injecting the snippet through a directive, but without luck.

**Comment by DanWilkerson** [comment]
That's outside of the purview of Angulartics,  I'm afraid - we leave it to you to load the libraries and configure them. 

You might try just editing the snippet to do something like this:

    var containerId = document.location.hostname === 'example.com' ? 'GTM-1234' : 'GTM-5678';
    
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
     new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
     j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
     'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
     })(window,document,'script','dataLayer',containerId);</script>
