### ISSUE TITLE
Tag manager events are not getting fired 

### ISSUE THREAD

**Issue by Debananda** [angulartics/angulartics-google-tag-manager#23]
Triggers are not firing in interaction event. Below are the details

![image](https://user-images.githubusercontent.com/5937232/34287318-7f13c412-e70c-11e7-9ffa-a714e25c417c.png)

"angular": "^1.6.7",
"angulartics": "^1.5.0",
"angulartics-google-tag-manager": "0.0.1",

Variables 
`

Name | Type | Variable Name
-- | -- | --
angulartics page path | Data Layer Variable V2 | content-name
angulartics event category | Data Layer Variable V2 | target
angulartics event action | Data Layer Variable V2 | action
angulartics event label | Data Layer Variable V2 | target-properties
angulartics event value | Data Layer Variable V2 | value
angulartics event interaction type | Data Layer Variable V2 | interaction-type
angulartics user id | Data Layer Variable V2 | userId

`

Triggers
`

Name | Event | Event Name
-- | -- | --
Angulartics events | Custom Event | interaction
Angulartics pageviews | Custom Event | content-view

`

Name: Angulartics Events

    Product: Google Analytics
    Type: Universal Analytics
    Tracking ID: YourGoogleAnalyticsID
    Track Type: Event
    Category: {{angulartics event category}}
    Action: {{angulartics event action}}
    Label: {{angulartics event label}}
    Value: {{angulartics event value}}
    Non-Interaction Hit: {{angulartics event interaction type}}
    More settings > Fields to Set > name: page, value: {{angulartics page path}}
    More settings > Fields to Set > name: cookieDomain, value: auto
    More settings > Fields to Set > name: userID, value: {{angulartics user id}}
    Fire On: Angulartics events

**Comment by DanWilkerson** [comment]
How are you trying to call the event?

**Comment by Debananda** [comment]
I am using the below snippet to call the event
`<button analytics-on="click" 	analytics-event="Angulartics events" analytics-category="{{app.category}}" analytics-label="{{app.displayName}}" data-ng-click="$ctrl.gotoApp($index)">{{app.displayName}}</button>`

even I have tried with 
$analytics.eventTrack('interaction', {
      category: app.category, label: app.displayName
    });

**Comment by DanWilkerson** [comment]
Are there any exceptions in the console? Do you have the core lib and the
GTM module installed?

**Comment by Debananda** [comment]
nope there are no exceptions in the console. and tag manager is installed correctly. we have configured some other events with class name. those are working fine. we have just started looking into the angularjs implementation and facing this issue

**Comment by DanWilkerson** [comment]
Do you have both angulartics and angulartics-google-tag-manager required in your app? Beyond that, I'm not sure I can help here. The functionality in question has been used by many others without issue, so my suspicion is that the problem is specific to the implementation you're working with.
